/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as ApiCapacityAnalysisRouteImport } from './routes/api/capacity-analysis'
import { Route as BTokenRouteImport } from './routes/b/$token'
import { Route as CTokenRouteImport } from './routes/c/$token'
import { Route as ClinicCapacityRouteImport } from './routes/clinic.capacity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapacityAnalysisRoute = ApiCapacityAnalysisRouteImport.update({
  id: '/api/capacity-analysis',
  path: '/api/capacity-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BTokenRoute = BTokenRouteImport.update({
  id: '/b/$token',
  path: '/b/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicCapacityRoute = ClinicCapacityRouteImport.update({
  id: '/clinic/capacity',
  path: '/clinic/capacity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/api/capacity-analysis': typeof ApiCapacityAnalysisRoute
  '/b/$token': typeof BTokenRoute
  '/c/$token': typeof CTokenRoute
  '/clinic/capacity': typeof ClinicCapacityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/api/capacity-analysis': typeof ApiCapacityAnalysisRoute
  '/b/$token': typeof BTokenRoute
  '/c/$token': typeof CTokenRoute
  '/clinic/capacity': typeof ClinicCapacityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/api/capacity-analysis': typeof ApiCapacityAnalysisRoute
  '/b/$token': typeof BTokenRoute
  '/c/$token': typeof CTokenRoute
  '/clinic/capacity': typeof ClinicCapacityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/api/capacity-analysis'
    | '/b/$token'
    | '/c/$token'
    | '/clinic/capacity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/api/capacity-analysis'
    | '/b/$token'
    | '/c/$token'
    | '/clinic/capacity'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/api/capacity-analysis'
    | '/b/$token'
    | '/c/$token'
    | '/clinic/capacity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  ApiCapacityAnalysisRoute: typeof ApiCapacityAnalysisRoute
  BTokenRoute: typeof BTokenRoute
  CTokenRoute: typeof CTokenRoute
  ClinicCapacityRoute: typeof ClinicCapacityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/capacity-analysis': {
      id: '/api/capacity-analysis'
      path: '/api/capacity-analysis'
      fullPath: '/api/capacity-analysis'
      preLoaderRoute: typeof ApiCapacityAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$token': {
      id: '/b/$token'
      path: '/b/$token'
      fullPath: '/b/$token'
      preLoaderRoute: typeof BTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/capacity': {
      id: '/clinic/capacity'
      path: '/clinic/capacity'
      fullPath: '/clinic/capacity'
      preLoaderRoute: typeof ClinicCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  ApiCapacityAnalysisRoute: ApiCapacityAnalysisRoute,
  BTokenRoute: BTokenRoute,
  CTokenRoute: CTokenRoute,
  ClinicCapacityRoute: ClinicCapacityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
